apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app
          image: siwar97/devops:latest   # Your Docker image
          ports:
            - containerPort: 8089        # App port inside container
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/studentdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: secret
            - name: SERVER_PORT
              value: "8089"
